dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t "devops-course-for-trainees:$TRAVIS_BUILD_NUMBER"
      - docker tag devops-course-for-trainees:$TRAVIS_BUILD_NUMBER $DOCKER_USERNAME/devops-course-for-trainees
      - docker push $DOCKER_USERNAME/devops-course-for-trainees:latest
