dist: trusty

language: node_js

node_js:
 - "14"

jobs:
  include:
    - stage: test react app
      - npm test
    - stage: build react app
      - npm run build
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t devops-course-for-trainees:$TRAVIS_BUILD_NUMBER .
      - docker tag devops-course-for-trainees:$TRAVIS_BUILD_NUMBER $DOCKER_USERNAME/devops-course-for-trainees
      - docker push $DOCKER_USERNAME/devops-course-for-trainees:latest
